{{ if not .Values.admin.secured }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-user
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.admin.username }}
  admin-password: {{ .Values.admin.password }}
{{ end }}