nameOverride: "grafana"
grafana:
  admin:
    existingSecret: "grafana-admin-user"
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    log:
      level: warn
    log.console:
      format: json
    users:
      default_theme: light # dark | light
    auth.anonymous:
      enabled: false
  initChownData:
    enabled: false
  persistence:
    enabled: false
  plugins:
    - grafana-simple-json-datasource
    - yesoreyeram-infinity-datasource
  rbac:
    create: false
    pspEnabled: false
    namespaced: true
  securityContext: ""
  serviceAccount:
    create: true
    name: odala-developer

  sidecar:
    dashboards:
      #      enabled: true
      enabled: false
      #      SCProvider: true
      SCProvider: false
      label: grafana_dashboard
      labelValue: grafana
      orgid: 1
      defaultFolderName: default
    datasources:
      enabled: false
      label: grafana_datasource
      labelValue: grafana
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 10Mi
  #  dashboardProviders:
  #    dashboardproviders.yaml:
  #      apiVersion: 1
  #      providers:
  #        - name: 'dashboards'
  #          orgId: 1
  #          folder: 'Dashboards'
  #          type: file
  #          disableDeletion: true
  #          editable: false
  #          options:
  #            path: /tmp/dashboards/dashboards  # should match sidecar.dashboards.defaultFolderName
  #        - name: 'air-quality'
  #          orgId: 1
  #          folder: 'Air Quality'
  #          type: file
  #          disableDeletion: true
  #          editable: false
  #          options:
  #            path: /tmp/dashboards/air-quality  # should match sidecar.dashboards.defaultFolderName

  podLabels:
    odala/platform: fiware
    odala/component: visualization
    odala/subcomponent: ui
    odala/product: grafana
  serviceMonitor:
    enabled: false
    interval: 30s
  env:
    GF_PANELS_DISABLE_SANITIZE_HTML: true

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi

  ingress:
    enabled: true
    hosts:
      - grafana.staging.odala.kiel.de
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
      nginx.ingress.kubernetes.io/use-geoip: "false"
      nginx.ingress.kubernetes.io/use-geoip2: "true"

admin:
  secured: false
  username: fiwareAdmin
  password: fiwareAdmin

route:
  # -- To enable the OpenShift route
  enabled: false

datasources:
  enabled: false
  timescale:
    # -- Timescale URL
    url: tsdb
    # -- Timescale database name
    database: postgres
    credentials:
      # -- Timescale database username
      username: postgres
      # -- Timescale database password
      password: test

tests:
  enabled: false
